version: 0.2

phases:
  build:
    commands:
      - echo "Invalidate CloudFront cache"
      - echo "CF ID is $DISTRIBUTION_ID"
      - |
        aws cloudfront create-invalidation \
          --distribution-id $DISTRIBUTION_ID \
          --paths "/*"

      - echo "Invalidation submitted ✅"