version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"

  build:
    commands:
      - echo "Build phase"
      - sed -i 's/ENV_PLACEHOLDER/'"$ENVIRONMENT"'/g' index.html

  post_build:
    commands:
      - echo "Post build phase"

artifacts:
  base-directory: .
  files:
    - index.html
    - data/**/*
    - "buildspec/*"
    - "infra/*"
    - "*.yml"
    - "*.css"
    - "*.js"